version: "3.1"
services:
  postgres: 
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: actix
      POSTGRES_USER: actix
      POSTGRES_DB: actix
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5433
